abconsilium_homepage:
    path:     /
    defaults: { _controller: ABconsiliumBundle:Default:index }

index:
    path:     /admin
    defaults: { _controller: ABconsiliumBundle:Admin:index }

login:
    path:     /login
    defaults: { _controller: ABconsiliumBundle:Security:login }

logout:
    path: /logout
