abconsilium_homepage:
    path:     /
    defaults: { _controller: ABconsiliumBundle:Default:index }

index:
    path:     /admin
    defaults: { _controller: ABconsiliumBundle:Admin:index }

login:
    path:     /login
    defaults: { _controller: ABconsiliumBundle:Security:login }

logout:
    path: /logout

get_user:
    path:     /user/get
    defaults: { _controller: ABconsiliumBundle:User:getUser }

create_user:
    path:     /user/create
    defaults: { _controller: ABconsiliumBundle:User:createUser }

update_user:
    path:     /user/update
    defaults: { _controller: ABconsiliumBundle:User:updateUser }

delete_user:
    path:     /user/delete
    defaults: { _controller: ABconsiliumBundle:User:deleteUser }