security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: ABconsiliumBundle:User
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ABconsiliumBundle\Entity\User: plaintext

    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            pattern:    ^/
            provider: our_db_provider

#        secured_area:
#            logout:
#                path: /logout
#                target: /

    access_control:
            - { path: ^/admin, roles: ROLE_USER }
