security:

    providers:
        our_db_provider:
            entity:
                class: ABconsiliumBundle:User
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ABconsiliumBundle\Entity\User: plaintext

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: login
                check_path: login

            pattern:    ^/
            provider: our_db_provider

            logout:
                path: /logout
                target: /

    access_control:
            - { path: ^/admin, roles: ROLE_USER }
