<?php

namespace ABconsiliumBundle\Repository;

/**
 * AimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AimRepository extends \Doctrine\ORM\EntityRepository
{
}
